# Generated by Django 4.2.29 on 2026-04-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_id', models.CharField(max_length=20, unique=True, verbose_name='الرقم الأكاديمي')),
                ('full_name', models.CharField(max_length=100, verbose_name='الاسم الكامل')),
                ('grade_level', models.CharField(max_length=50, verbose_name='الصف الدراسي')),
                ('class_id', models.CharField(blank=True, max_length=50, verbose_name='معرف الشعبة')),
                ('class_name', models.CharField(blank=True, max_length=100, verbose_name='اسم الشعبة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'طالب',
                'verbose_name_plural': 'الطلاب',
            },
        ),
    ]
