# Generated by Django 4.2.29 on 2026-04-01 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=20, unique=True, verbose_name='الرقم الوظيفي')),
                ('password', models.CharField(max_length=128, verbose_name='كلمة المرور')),
                ('full_name', models.CharField(max_length=100, verbose_name='الاسم الكامل')),
                ('subject', models.CharField(max_length=100, verbose_name='المادة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'معلم',
                'verbose_name_plural': 'المعلمون',
            },
        ),
        migrations.CreateModel(
            name='TeacherClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(max_length=50, verbose_name='معرف الشعبة')),
                ('class_name', models.CharField(max_length=100, verbose_name='اسم الشعبة')),
                ('students_count', models.PositiveIntegerField(default=0, verbose_name='عدد الطلاب')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'شعبة المعلم',
                'verbose_name_plural': 'شعب المعلمين',
                'unique_together': {('teacher', 'class_id')},
            },
        ),
    ]
