# Generated by Django 6.0.1 on 2026-01-12 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الكتاب')),
                ('term', models.CharField(choices=[('first', 'الفصل الدراسي الأول'), ('second', 'الفصل الدراسي الثاني')], max_length=20, verbose_name='الفصل الدراسي')),
                ('total_pages', models.PositiveIntegerField(verbose_name='عدد الصفحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='curriculum.subject', verbose_name='المادة')),
            ],
        ),
    ]
