# Generated by Django 6.0.1 on 2026-01-12 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الملخص')),
                ('summary_type', models.PositiveSmallIntegerField(choices=[(1, 'الملخص الأول'), (2, 'الملخص الثاني'), (3, 'الملخص الثالث')], verbose_name='نوع الملخص')),
                ('content', models.TextField(verbose_name='محتوى الملخص')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='curriculum.book', verbose_name='الكتاب')),
            ],
        ),
    ]
