# Generated by Django 6.0.1 on 2026-01-14 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('content_html', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='curriculum.book')),
            ],
            options={
                'ordering': ['page_number'],
                'unique_together': {('book', 'page_number')},
            },
        ),
        migrations.CreateModel(
            name='OldSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary_type', models.PositiveSmallIntegerField(choices=[(1, 'الملخص الأول'), (2, 'الملخص الثاني'), (3, 'الملخص الثالث')])),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_summaries', to='curriculum.book', verbose_name='الكتاب')),
            ],
        ),
        migrations.CreateModel(
            name='PageSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_type', models.PositiveSmallIntegerField(choices=[(1, 'الملخص الأول'), (2, 'الملخص الثاني'), (3, 'الملخص الثالث')])),
                ('book_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='curriculum.bookpage')),
            ],
            options={
                'ordering': ['summary_type'],
                'unique_together': {('book_page', 'summary_type')},
            },
        ),
        migrations.CreateModel(
            name='PageSummaryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_order', models.PositiveIntegerField()),
                ('content_html', models.TextField()),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='curriculum.pagesummary')),
            ],
            options={
                'ordering': ['page_order'],
                'unique_together': {('summary', 'page_order')},
            },
        ),
        migrations.DeleteModel(
            name='Summary',
        ),
    ]
