# Generated by Django 6.0.1 on 2026-03-06 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_bookpage_oldsummary_pagesummary_pagesummarypage_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pagesummarypage',
            index=models.Index(fields=['summary', 'page_order'], name='curriculum__summary_8ccbee_idx'),
        ),
    ]
