# Generated by Django 6.0.1 on 2026-03-06 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_pagesummarypage_curriculum__summary_8ccbee_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pagesummary',
            index=models.Index(fields=['book_page', 'summary_type'], name='curriculum__book_pa_c86784_idx'),
        ),
    ]
