# Generated by Django 4.2.29 on 2026-04-01 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0006_pagesummary_curriculum__book_pa_c86784_idx'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_id', models.CharField(db_index=True, max_length=20, verbose_name='الرقم الأكاديمي')),
                ('last_page', models.PositiveIntegerField(default=1, verbose_name='آخر صفحة')),
                ('pages_read', models.PositiveIntegerField(default=0, verbose_name='عدد الصفحات المفتوحة')),
                ('total_time_minutes', models.PositiveIntegerField(default=0, verbose_name='إجمالي وقت القراءة (دقيقة)')),
                ('interaction_score', models.PositiveIntegerField(default=0, verbose_name='نقاط التفاعل')),
                ('progress_percent', models.FloatField(default=0.0, verbose_name='نسبة الإنجاز')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='curriculum.book', verbose_name='الكتاب')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'تقدم الطالب',
                'verbose_name_plural': 'تقدم الطلاب',
                'indexes': [models.Index(fields=['academic_id'], name='progress_pr_academi_4bd778_idx')],
                'unique_together': {('academic_id', 'book')},
            },
        ),
    ]
