# Generated by Django 4.2.29 on 2026-04-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.CharField(max_length=20, unique=True, verbose_name='رقم ولي الأمر')),
                ('full_name', models.CharField(max_length=100, verbose_name='الاسم الكامل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('children', models.ManyToManyField(blank=True, related_name='parents', to='students.student', verbose_name='الأبناء')),
            ],
            options={
                'verbose_name': 'ولي الأمر',
                'verbose_name_plural': 'أولياء الأمور',
            },
        ),
    ]
